### ISSUE TITLE
About object detection?

### ISSUE THREAD

**Issue by nooralahzadeh** [zmykevin/UC2#6]
Hi,
Thanks for sharing the code of this amazing multimodal and multilingual method.
I wonder how I can find the code where you applied the object detector to label an image region (top-1 or soft-label) in `Masked Region-to-Token Modeling`?
Thanks,

**Comment by zmykevin** [comment]
The object detector is already applied to generate the visual features. The visual features  contains the object detection result. Regarding  the  details of the  object  detector and how the visual features are generated, please refer to the repo of  [UNITER](https://github.com/ChenRocks/UNITER)
