### ISSUE TITLE
How did you do MT

### ISSUE THREAD

**Issue by BUAADreamer** [zmykevin/UC2#8]
Hello, I want to know how did you do your machine translation so I can extend this model to more languages, which I cannot find in paper and this repo.
What I was asking are as follows:
* What MT tools/interface (eg. baidu/google translation)
* What version (eg. free/vip)
Thank you!

**Comment by zmykevin** [comment]
Hi,  I am using the machine translation API from [Microsoft Azure](https://www.microsoft.com/en-us/translator/business/translator-api/). As the work is done during my internship at Microsoft, so it does not really cost any money to use them as an internal tool. There are some recent work that translates the CC into more languages: [Multilingual Multimodal Learning with Machine Translated Text](https://arxiv.org/pdf/2210.13134.pdf), which you might be interested to taking a look at before you translate CC to more languages.

**Comment by BUAADreamer** [comment]
Thanks for such comprehensive answer!
